### ISSUE TITLE
Merge into Map using object notation in patch

### ISSUE THREAD

**Issue by kf6kjg** [QuentinRoy/tiny-merge-patch#24]
It'd be great if the library understood that it was merging into one of the newer data structure objects, such as Map, and acted appropriately.  Of course JSON Merge Patch has no semantic for "insert key between these keys" or even a related semantic that I'm aware of, but on inserts it could simply append the new entries.

As it stands this simply replaces the Map with whatever came in the patch, destroying the data that was there.

Here's a set of tests I whipped up to demonstrate the issue:
[index.js.txt](https://github.com/QuentinRoy/tiny-merge-patch/files/3336770/index.js.txt)
[runTest.js.txt](https://github.com/QuentinRoy/tiny-merge-patch/files/3336771/runTest.js.txt)
[testInsert.js.txt](https://github.com/QuentinRoy/tiny-merge-patch/files/3336772/testInsert.js.txt)
[testUpdate.js.txt](https://github.com/QuentinRoy/tiny-merge-patch/files/3336773/testUpdate.js.txt)

**Comment by QuentinRoy** [comment]
Yes, right now the library only supports plain old objects, and arrays. Its goal is to be strictly compliant with [RFC 7396](https://tools.ietf.org/html/rfc7396), which is about JSON. So it does not support `Map`.
